#!/bin/sh

# This script verifies that the postgresql data directory has been correctly
# initialized.  We do not want to automatically initdb it, because that has
# a risk of catastrophic failure (ie, overwriting a valuable database) in
# corner cases, such as a remotely mounted database on a volume that's a
# bit slow to mount.  But we can at least emit a message advising newbies
# what to do.

PGDATA="$1"

if [ -z "$PGDATA" ]
then
    echo "Usage: $0 database-path"
    exit 1
fi

if [ ! -d "$PGDATA/base" ]
then
    # No existing PGDATA! Warn the user to initdb it.
    echo $"\"$PGDATA\" is missing or empty. Use a command like"
    echo $"  su - postgres -c \"initdb --locale en_US.UTF-8 -D '$PGDATA'\""
    echo $"with relevant options, to initialize the database cluster."
    exit 1
fi

exit 0
